
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - image: mmassolit/payment
          name: payment
          ports:
            - containerPort: 8086
              name: payment
          env:
            - name: POSTGRES_ENDPOINT
              value: "jdbc:postgresql://127.0.0.1:5432/payment_service"
            - name: POSTGRES_PASSWORD
              value: "123"
            - name: POSTGRES_USERNAME
              value: "video_sharing_test"